// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientFollowerProtocol.proto

package com.bbles.automator.node.protobuf;

public final class ClientFollowerProtocol {
  private ClientFollowerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ClientFollowerProtocol.proto\022!com.bble" +
      "s.automator.node.protobuf\032\rgeneral.proto" +
      "2\206\001\n\025ClientFollowerService\022m\n\tgetStatus\022" +
      "1.com.bbles.automator.node.protobuf.Task" +
      "Descriptor\032-.com.bbles.automator.node.pr" +
      "otobuf.TaskStatusP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bbles.automator.node.protobuf.GeneralProtocol.getDescriptor(),
        }, assigner);
    com.bbles.automator.node.protobuf.GeneralProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
