// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMasterProtocol.proto

package com.bbles.automator.node.protobuf;

public final class ClientMasterProtocol {
  private ClientMasterProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ClientMasterProtocol.proto\022!com.bbles." +
      "automator.node.protobuf\032\rgeneral.proto2\201" +
      "\001\n\023ClientMasterService\022j\n\007execute\022..com." +
      "bbles.automator.node.protobuf.TaskWrappe" +
      "r\032-.com.bbles.automator.node.protobuf.Ta" +
      "skOutput0\001P\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bbles.automator.node.protobuf.GeneralProtocol.getDescriptor(),
        }, assigner);
    com.bbles.automator.node.protobuf.GeneralProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
