// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MasterFollowerProtocol.proto

package com.bbles.automator.node.protobuf;

public final class MasterFollowerProtocol {
  private MasterFollowerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProcessorKernelAuthenticateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes krb_token = 1;</code>
     */
    boolean hasKrbToken();
    /**
     * <code>required bytes krb_token = 1;</code>
     */
    com.google.protobuf.ByteString getKrbToken();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate}
   */
  public  static final class ProcessorKernelAuthenticate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate)
      ProcessorKernelAuthenticateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProcessorKernelAuthenticate.newBuilder() to construct.
    private ProcessorKernelAuthenticate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProcessorKernelAuthenticate() {
      krbToken_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProcessorKernelAuthenticate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              krbToken_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.class, com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.Builder.class);
    }

    private int bitField0_;
    public static final int KRB_TOKEN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString krbToken_;
    /**
     * <code>required bytes krb_token = 1;</code>
     */
    public boolean hasKrbToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes krb_token = 1;</code>
     */
    public com.google.protobuf.ByteString getKrbToken() {
      return krbToken_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKrbToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, krbToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, krbToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate)) {
        return super.equals(obj);
      }
      com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate other = (com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate) obj;

      boolean result = true;
      result = result && (hasKrbToken() == other.hasKrbToken());
      if (hasKrbToken()) {
        result = result && getKrbToken()
            .equals(other.getKrbToken());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKrbToken()) {
        hash = (37 * hash) + KRB_TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getKrbToken().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate)
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.class, com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.Builder.class);
      }

      // Construct using com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        krbToken_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_descriptor;
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate getDefaultInstanceForType() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.getDefaultInstance();
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate build() {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate buildPartial() {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate result = new com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.krbToken_ = krbToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate) {
          return mergeFrom((com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate other) {
        if (other == com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate.getDefaultInstance()) return this;
        if (other.hasKrbToken()) {
          setKrbToken(other.getKrbToken());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKrbToken()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString krbToken_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes krb_token = 1;</code>
       */
      public boolean hasKrbToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes krb_token = 1;</code>
       */
      public com.google.protobuf.ByteString getKrbToken() {
        return krbToken_;
      }
      /**
       * <code>required bytes krb_token = 1;</code>
       */
      public Builder setKrbToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        krbToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes krb_token = 1;</code>
       */
      public Builder clearKrbToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        krbToken_ = getDefaultInstance().getKrbToken();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate)
    }

    // @@protoc_insertion_point(class_scope:com.bbles.automator.node.protobuf.ProcessorKernelAuthenticate)
    private static final com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate();
    }

    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProcessorKernelAuthenticate>
        PARSER = new com.google.protobuf.AbstractParser<ProcessorKernelAuthenticate>() {
      public ProcessorKernelAuthenticate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProcessorKernelAuthenticate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProcessorKernelAuthenticate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessorKernelAuthenticate> getParserForType() {
      return PARSER;
    }

    public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelAuthenticate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProcessorKernelDelegationTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>required bytes token = 1;</code>
     */
    com.google.protobuf.ByteString getToken();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken}
   */
  public  static final class ProcessorKernelDelegationToken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken)
      ProcessorKernelDelegationTokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProcessorKernelDelegationToken.newBuilder() to construct.
    private ProcessorKernelDelegationToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProcessorKernelDelegationToken() {
      token_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProcessorKernelDelegationToken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.class, com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.Builder.class);
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString token_;
    /**
     * <code>required bytes token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes token = 1;</code>
     */
    public com.google.protobuf.ByteString getToken() {
      return token_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, token_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, token_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken)) {
        return super.equals(obj);
      }
      com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken other = (com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken) obj;

      boolean result = true;
      result = result && (hasToken() == other.hasToken());
      if (hasToken()) {
        result = result && getToken()
            .equals(other.getToken());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken)
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.class, com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.Builder.class);
      }

      // Construct using com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        token_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_descriptor;
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken getDefaultInstanceForType() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.getDefaultInstance();
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken build() {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken buildPartial() {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken result = new com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken) {
          return mergeFrom((com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken other) {
        if (other == com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToken()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString token_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes token = 1;</code>
       */
      public com.google.protobuf.ByteString getToken() {
        return token_;
      }
      /**
       * <code>required bytes token = 1;</code>
       */
      public Builder setToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken)
    }

    // @@protoc_insertion_point(class_scope:com.bbles.automator.node.protobuf.ProcessorKernelDelegationToken)
    private static final com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken();
    }

    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProcessorKernelDelegationToken>
        PARSER = new com.google.protobuf.AbstractParser<ProcessorKernelDelegationToken>() {
      public ProcessorKernelDelegationToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProcessorKernelDelegationToken(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProcessorKernelDelegationToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessorKernelDelegationToken> getParserForType() {
      return PARSER;
    }

    public com.bbles.automator.node.protobuf.MasterFollowerProtocol.ProcessorKernelDelegationToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskRepresenterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbles.automator.node.protobuf.TaskRepresenter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string taskType = 1;</code>
     */
    boolean hasTaskType();
    /**
     * <code>required string taskType = 1;</code>
     */
    java.lang.String getTaskType();
    /**
     * <code>required string taskType = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskTypeBytes();

    /**
     * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
     */
    boolean hasTask();
    /**
     * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
     */
    com.bbles.automator.node.protobuf.ClientMasterProtocol.Task getTask();
    /**
     * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
     */
    com.bbles.automator.node.protobuf.ClientMasterProtocol.TaskOrBuilder getTaskOrBuilder();
  }
  /**
   * Protobuf type {@code com.bbles.automator.node.protobuf.TaskRepresenter}
   */
  public  static final class TaskRepresenter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbles.automator.node.protobuf.TaskRepresenter)
      TaskRepresenterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskRepresenter.newBuilder() to construct.
    private TaskRepresenter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskRepresenter() {
      taskType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskRepresenter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              taskType_ = bs;
              break;
            }
            case 18: {
              com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = task_.toBuilder();
              }
              task_ = input.readMessage(com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(task_);
                task_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.class, com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.Builder.class);
    }

    private int bitField0_;
    public static final int TASKTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskType_;
    /**
     * <code>required string taskType = 1;</code>
     */
    public boolean hasTaskType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string taskType = 1;</code>
     */
    public java.lang.String getTaskType() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTypeBytes() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_FIELD_NUMBER = 2;
    private com.bbles.automator.node.protobuf.ClientMasterProtocol.Task task_;
    /**
     * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
     */
    public boolean hasTask() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
     */
    public com.bbles.automator.node.protobuf.ClientMasterProtocol.Task getTask() {
      return task_ == null ? com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.getDefaultInstance() : task_;
    }
    /**
     * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
     */
    public com.bbles.automator.node.protobuf.ClientMasterProtocol.TaskOrBuilder getTaskOrBuilder() {
      return task_ == null ? com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.getDefaultInstance() : task_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaskType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTask().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getTask());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTask());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter)) {
        return super.equals(obj);
      }
      com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter other = (com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter) obj;

      boolean result = true;
      result = result && (hasTaskType() == other.hasTaskType());
      if (hasTaskType()) {
        result = result && getTaskType()
            .equals(other.getTaskType());
      }
      result = result && (hasTask() == other.hasTask());
      if (hasTask()) {
        result = result && getTask()
            .equals(other.getTask());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTaskType()) {
        hash = (37 * hash) + TASKTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTaskType().hashCode();
      }
      if (hasTask()) {
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTask().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbles.automator.node.protobuf.TaskRepresenter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbles.automator.node.protobuf.TaskRepresenter)
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.class, com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.Builder.class);
      }

      // Construct using com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTaskFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        taskType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (taskBuilder_ == null) {
          task_ = null;
        } else {
          taskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_descriptor;
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter getDefaultInstanceForType() {
        return com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.getDefaultInstance();
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter build() {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter buildPartial() {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter result = new com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskType_ = taskType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (taskBuilder_ == null) {
          result.task_ = task_;
        } else {
          result.task_ = taskBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter) {
          return mergeFrom((com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter other) {
        if (other == com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter.getDefaultInstance()) return this;
        if (other.hasTaskType()) {
          bitField0_ |= 0x00000001;
          taskType_ = other.taskType_;
          onChanged();
        }
        if (other.hasTask()) {
          mergeTask(other.getTask());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskType()) {
          return false;
        }
        if (!hasTask()) {
          return false;
        }
        if (!getTask().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskType_ = "";
      /**
       * <code>required string taskType = 1;</code>
       */
      public boolean hasTaskType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string taskType = 1;</code>
       */
      public java.lang.String getTaskType() {
        java.lang.Object ref = taskType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taskType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskTypeBytes() {
        java.lang.Object ref = taskType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskType = 1;</code>
       */
      public Builder setTaskType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskType = 1;</code>
       */
      public Builder clearTaskType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskType_ = getDefaultInstance().getTaskType();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskType = 1;</code>
       */
      public Builder setTaskTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskType_ = value;
        onChanged();
        return this;
      }

      private com.bbles.automator.node.protobuf.ClientMasterProtocol.Task task_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bbles.automator.node.protobuf.ClientMasterProtocol.Task, com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.Builder, com.bbles.automator.node.protobuf.ClientMasterProtocol.TaskOrBuilder> taskBuilder_;
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public boolean hasTask() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public com.bbles.automator.node.protobuf.ClientMasterProtocol.Task getTask() {
        if (taskBuilder_ == null) {
          return task_ == null ? com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.getDefaultInstance() : task_;
        } else {
          return taskBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public Builder setTask(com.bbles.automator.node.protobuf.ClientMasterProtocol.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          task_ = value;
          onChanged();
        } else {
          taskBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public Builder setTask(
          com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          task_ = builderForValue.build();
          onChanged();
        } else {
          taskBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public Builder mergeTask(com.bbles.automator.node.protobuf.ClientMasterProtocol.Task value) {
        if (taskBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              task_ != null &&
              task_ != com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.getDefaultInstance()) {
            task_ =
              com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.newBuilder(task_).mergeFrom(value).buildPartial();
          } else {
            task_ = value;
          }
          onChanged();
        } else {
          taskBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public Builder clearTask() {
        if (taskBuilder_ == null) {
          task_ = null;
          onChanged();
        } else {
          taskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.Builder getTaskBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTaskFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      public com.bbles.automator.node.protobuf.ClientMasterProtocol.TaskOrBuilder getTaskOrBuilder() {
        if (taskBuilder_ != null) {
          return taskBuilder_.getMessageOrBuilder();
        } else {
          return task_ == null ?
              com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.getDefaultInstance() : task_;
        }
      }
      /**
       * <code>required .com.bbles.automator.node.protobuf.Task task = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bbles.automator.node.protobuf.ClientMasterProtocol.Task, com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.Builder, com.bbles.automator.node.protobuf.ClientMasterProtocol.TaskOrBuilder> 
          getTaskFieldBuilder() {
        if (taskBuilder_ == null) {
          taskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bbles.automator.node.protobuf.ClientMasterProtocol.Task, com.bbles.automator.node.protobuf.ClientMasterProtocol.Task.Builder, com.bbles.automator.node.protobuf.ClientMasterProtocol.TaskOrBuilder>(
                  getTask(),
                  getParentForChildren(),
                  isClean());
          task_ = null;
        }
        return taskBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbles.automator.node.protobuf.TaskRepresenter)
    }

    // @@protoc_insertion_point(class_scope:com.bbles.automator.node.protobuf.TaskRepresenter)
    private static final com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter();
    }

    public static com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TaskRepresenter>
        PARSER = new com.google.protobuf.AbstractParser<TaskRepresenter>() {
      public TaskRepresenter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskRepresenter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskRepresenter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskRepresenter> getParserForType() {
      return PARSER;
    }

    public com.bbles.automator.node.protobuf.MasterFollowerProtocol.TaskRepresenter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034MasterFollowerProtocol.proto\022!com.bble" +
      "s.automator.node.protobuf\032\032ClientMasterP" +
      "rotocol.proto\">\n\033ProcessorKernelAuthenti" +
      "cate\022\021\n\tkrb_token\030\001 \002(\014\022\014\n\004name\030\002 \002(\t\"=\n" +
      "\036ProcessorKernelDelegationToken\022\r\n\005token" +
      "\030\001 \002(\014\022\014\n\004name\030\002 \002(\t\"Z\n\017TaskRepresenter\022" +
      "\020\n\010taskType\030\001 \002(\t\0225\n\004task\030\002 \002(\0132\'.com.bb" +
      "les.automator.node.protobuf.Task2\205\001\n\026Ker" +
      "nelProcessorService\022k\n\006submit\022..com.bble" +
      "s.automator.node.protobuf.TaskWrapper\0321." +
      "com.bbles.automator.node.protobuf.TaskDe" +
      "scriptorP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bbles.automator.node.protobuf.ClientMasterProtocol.getDescriptor(),
        }, assigner);
    internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbles_automator_node_protobuf_ProcessorKernelAuthenticate_descriptor,
        new java.lang.String[] { "KrbToken", "Name", });
    internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbles_automator_node_protobuf_ProcessorKernelDelegationToken_descriptor,
        new java.lang.String[] { "Token", "Name", });
    internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbles_automator_node_protobuf_TaskRepresenter_descriptor,
        new java.lang.String[] { "TaskType", "Task", });
    com.bbles.automator.node.protobuf.ClientMasterProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
